apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-role-rx
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::492266378106:role/external-dns-role-rx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-role-rx
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-role-rx
subjects:
- kind: ServiceAccount
  name: external-dns-role-rx
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-role-rx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-role-rx
  template:
    metadata:
      labels:
        app: external-dns-role-rx
    spec:
      serviceAccountName: external-dns-role-rx
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.6
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=training.trambo.cloud # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
        - --registry=txt
        - --txt-owner-id=my-hostedzone-identifier
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files