apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deployment
spec:
  template:
    metadata:
      name: hpa-container
      labels:
        app: hpa
    spec:
      containers:
        - name: hpa-example
          image: k8s.gcr.io/hpa-example
          resources:
            requests:
              cpu: "300m"
            limits:
              cpu: "400m"
  replicas: 1
  selector:
    matchLabels:
      app: hpa